--- JOIN과 LIKE 사용
SELECT A_O.ANIMAL_ID, A_O.ANIMAL_TYPE, A_O.NAME
FROM ANIMAL_OUTS AS A_O JOIN ANIMAL_INS AS A_I
ON A_I.ANIMAL_ID = A_O.ANIMAL_ID
WHERE A_I.SEX_UPON_INTAKE LIKE ('Intact%') AND
    (A_O.SEX_UPON_OUTCOME LIKE('Spayed%') OR A_O.SEX_UPON_OUTCOME LIKE ('Neutered%'))
ORDER BY A_O.ANIMAL_ID

--- JOIN과 IN,NOT IN 사용
SELECT A_O.ANIMAL_ID, A_O.ANIMAL_TYPE, A_O.NAME
FROM ANIMAL_OUTS AS A_O JOIN ANIMAL_INS AS A_I
ON A_I.ANIMAL_ID = A_O.ANIMAL_ID
WHERE A_I.SEX_UPON_INTAKE IN ('Intact Male', 'Intact Female')
AND A_O.SEX_UPON_OUTCOME NOT IN ('Intact Male', 'Intact Female')
ORDER BY A_O.ANIMAL_ID

--- JOIN과 != 사용해서 간단하게 풀기
SELECT A_O.ANIMAL_ID, A_O.ANIMAL_TYPE, A_O.NAME
FROM ANIMAL_OUTS AS A_O JOIN ANIMAL_INS AS A_I
ON A_I.ANIMAL_ID = A_O.ANIMAL_ID
WHERE A_I.SEX_UPON_INTAKE != A_O.SEX_UPON_OUTCOME
ORDER BY A_O.ANIMAL_ID