--- LIMIT로 풀기
SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME ASC
LIMIT 1

---RANK로 풀기
SELECT NAME
FROM (
    SELECT NAME, RANK() OVER(ORDER BY DATETIME ASC) AS RN
    FROM ANIMAL_INS
) AS A
WHERE A.RN = 1