--- JOIN과 LIMIT 이용
SELECT A_I.NAME, A_I.DATETIME
FROM ANIMAL_INS AS A_I LEFT JOIN ANIMAL_OUTS AS A_O
ON A_I.ANIMAL_ID = A_O.ANIMAL_ID
WHERE A_O.ANIMAL_ID IS NULL
ORDER BY A_I.DATETIME
LIMIT 3

--- JOIN과 NOT IN 이용
SELECT A_I.NAME, A_I.DATETIME
FROM ANIMAL_INS AS A_I
WHERE ANIMAL_ID NOT IN (
    SELECT A_O.ANIMAL_ID
    FROM ANIMAL_OUTS AS A_O
)
ORDER BY A_I.DATETIME
LIMIT 3

--- RANK 이용
SELECT A.NAME, A.DATETIME
FROM (
    SELECT A_I.NAME, A_I.DATETIME, RANK() OVER(ORDER BY DATETIME ASC) AS RN
    FROM ANIMAL_INS AS A_I LEFT JOIN ANIMAL_OUTS AS A_O
    ON A_I.ANIMAL_ID = A_O.ANIMAL_ID
    WHERE A_O.ANIMAL_ID IS NULL
) AS A
WHERE A.RN BETWEEN 1 AND 3

