--- DATEDIFF와 LIMIT 사용
SELECT A_O.ANIMAL_ID, A_O.NAME
FROM ANIMAL_INS AS A_I JOIN ANIMAL_OUTS AS A_O
ON A_I.ANIMAL_ID = A_O.ANIMAL_ID
ORDER BY DATEDIFF(A_O.DATETIME, A_I.DATETIME) DESC
LIMIT 2

--- DATEDIFF와 RANK 사용
SELECT A.ANIMAL_ID, A.NAME
FROM (
    SELECT A_I.ANIMAL_ID, A_I.NAME, RANK() OVER(ORDER BY DATEDIFF(A_O.DATETIME, A_I.DATETIME) DESC) AS RN
    FROM ANIMAL_INS AS A_I JOIN ANIMAL_OUTS AS A_O
    ON A_I.ANIMAL_ID = A_O.ANIMAL_ID
) A
WHERE A.RN BETWEEN 1 AND 2B