--- IS NULL
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NULL
ORDER BY ANIMAL_ID

--- SUBQUERY를 이용한 차집합

SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN(
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
    WHERE NAME IS NOT NULL
)
ORDER BY ANIMAL_ID