--- DATE_FORMAT 사용해서 형 변환
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME, '%Y-%m-%d') AS 날짜
FROM ANIMAL_INS
ORDER BY ANIMAL_ID

--- SUBSTRING을 사용해 문자열 슬라이싱
SELECT ANIMAL_ID, NAME, SUBSTRING(DATETIME, 1, 10) AS '날짜'
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;