SELECT ANIMAL_TYPE, COUNT(*) AS 'count'
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE

--- 문제 오류 (동물보호소에 고양이와 개 이외의 동물이 있을 수 있음으로 Where 절을 이용해야 함)

SELECT ANIMAL_TYPE, COUNT(*) AS 'count'
FROM ANIMAL_INS
WHERE ANIMAL_TYPE IN ('Cat', 'Dog')
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE