---LIMIT로 풀기
SELECT DATETIME AS 시간
FROM ANIMAL_INS
ORDER BY DATETIME ASC
LIMIT 1

---MIN으로 풀기
SELECT MIN(DATETIME) AS 시간
FROM ANIMAL_INS

---RANK로 풀기
SELECT DATETIME AS 시간
FROM (
    SELECT DATETIME, RANK() OVER(ORDER BY DATETIME ASC) AS RN
    FROM ANIMAL_INS
) AS A
WHERE A.RN = 1