--- RIGHT JOIN 이용 (JOIN 조건을 ON에 기술)
SELECT A_O.ANIMAL_ID, A_O.NAME
FROM ANIMAL_INS AS A_I RIGHT JOIN ANIMAL_OUTS AS A_O ON (A_I.ANIMAL_ID = A_O.ANIMAL_ID)
WHERE A_I.ANIMAL_ID IS NULL
ORDER BY ANIMAL_ID

--- SUBQUERY와 NOT IN 이용
SELECT ANIMAL_ID, NAME
FROM ANIMAL_OUTS
WHERE ANIMAL_ID NOT IN (
    SELECT ANIMAL_ID
    FROM ANIMAL_INS
)