--- LIMIT로 풀기
SELECT DATETIME AS 시간
FROM ANIMAL_INS
ORDER BY DATETIME DESC
LIMIT 1

---MAX로 풀기
SELECT MAX(DATETIME) AS 시간
FROM ANIMAL_INS

---RANK로 풀기
SELECT DATETIME AS 시간
FROM (
    SELECT DATETIME, RANK() OVER(ORDER BY DATETIME DESC) AS RN
    FROM ANIMAL_INS
) AS A
WHERE A.RN = 1